### PR TITLE
Changed String arguments to const String & and WiFiClient argument to…

### PR DESCRIPTION
**Pull request by jlbirccyn**
… WiFiClient & in order to avoid copies

Hello,

Following my contact by mail, here are the modifications made. VSCode has also changed the formatting. Sorry 😕

Changes are in branch 'references'

Sincerely

### CODE REVIEW

**Comment by LennartHennigs** [comment]
Hey, thank you. As you mention, this is a code breaking change but only a small update. So I'll integrate it when I do a major update and a version number increase. 
But it is on the list. 
Cheers
l.

**Comment by jlbirccyn** [comment]
Hello.
Do you have an idea of the approximate release date of the next major update? Indeed, I am writing an article for Locoduino (https://www.locoduino.org) and I wanted to know if I would present the current version or if I would wait a bit.

**Comment by LennartHennigs** [comment]
Hey Jean-Luc,
As I am doing this in my free time I cannot give you a date, unfortunately. Just use the current version. 
People will be notified in the Arduino or PlatformIO Ide of Updates when they download the library. 
And thank you for planning to mention it. 

Cheers 
l.

**Comment by LennartHennigs** [comment]
Hey, added your changes (plus a few other ones) but I will not use your branch, as it would break my formatting.

**Pull request closed without merging**
