### PR TITLE
Made the newline character configurable 

### PR DESCRIPTION
**Pull request by FunDeckHermit**
In my application the newline isn't '\n' and maybe there are some other people who have the same requirement. 

When okay'ed I'll also add these functions to the Readme. 

I'm not used to making Pull Requests, please tell me if I'm doing something wrong.

### CODE REVIEW

**Comment by LennartHennigs** [comment]
Hey. 
Thank your for the PR. 
I think that is this a decent addition. Yes, feel free to update the Readme and the channelog. 

I can merge that later using your PR and branch. 
Cheers

**Comment by FunDeckHermit** [comment]
I've modified the Readme and also took the liberty to expand some if it. 
Do you prefer `setNewLineCharacter` or `setNewlineCharacter` (lowercase **L**) ?

**Comment by LennartHennigs** [comment]
Thank you. 
I appreciate this. 
Newline

**Comment by FunDeckHermit** [comment]
Hi Lennart,

It should be ready for review and merging!

**Comment by FunDeckHermit** [comment]
Hi Lennart,

Could you approve the PR and make a new release?

**Review by LennartHennigs — APPROVED** [review]

**Comment by LennartHennigs** [comment]
Hey Roy, 
thanks again. Just merger your PR and some other small update.
It's now part of 2.2.2.

Cheers
l.

**Pull request merged**
